### ISSUE TITLE
Failed to run demo_mcmot.py, Unexpected key(s) in state_dict: "mtl_loss.sigma".

### ISSUE THREAD

**Issue by nicken** [CaptainEven/MCMOT-ByteTrack#10]
when i want run the demo file `python demo_mcmot.py`, i get this message:
```
2022-03-20 17:34:04.333 | INFO     | yolox.exp.build:get_exp_by_file:17 - Exp file path: /home/nicken/ai/cv_task/Object_Tracking/repository/MCMOT-ByteTrack/exps/example/mot/yolox_tiny_track_c5_darknet.py.
2022-03-20 17:34:04.333 | INFO     | yolox.exp.build:get_exp_by_file:20 - Exp file's dir path: /home/nicken/ai/cv_task/Object_Tracking/repository/MCMOT-ByteTrack/exps/example/mot.
2022-03-20 17:34:04.333 | INFO     | yolox.exp.build:get_exp_by_file:25 - Module name: yolox_tiny_track_c5_darknet.
{0: 1266, 1: 313, 2: 490, 3: 758, 4: 82}
ReID:  False
Number of classes:  5
2022-03-20 17:34:04.338 | INFO     | __main__:run:586 - Args: Namespace(camid=0, ckpt='../latest_ckpt.pth.tar', class_names=['car', ' bicycle', ' person', ' cyclist', ' tricycle'], conf=None, debug=True, demo='video', device='gpu', exp_file='../exps/example/mot/yolox_tiny_track_c5_darknet.py', experiment_name='yolox_tiny_track_c5_darknet', fp16=False, fuse=False, match_thresh=0.8, min_box_area=10, mot20=False, n_classes=5, name=None, nms=None, path='../videos/test_13.mp4', reid=False, save_result=True, task='track', track_buffer=240, track_thresh=0.5, trt=False, tsize=None, video_dir='../videos')
2022-03-20 17:34:04.342 | INFO     | yolox.models.yolox_darknet:__init__:753 - Network config file parsed.
2022-03-20 17:34:04.407 | INFO     | yolox.models.yolox_darknet:__init__:756 - Network modules built.
2022-03-20 17:34:04.407 | INFO     | yolox.models.yolox_darknet:__init__:760 - Network weights initialized.
2022-03-20 17:34:04.407 | INFO     | yolox.models.yolox_darknet:__init__:766 - Number of object classes: 5.
Net size:  (768, 448)
2022-03-20 17:34:04.407 | INFO     | yolox.models.yolox_darknet:__init__:773 - ReID: True
/home/nicken/.pyenv/versions/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
2022-03-20 17:34:06.095 | INFO     | __main__:run:601 - Model Summary: Params: 0.00M, Gflops: 0.00
2022-03-20 17:34:06.112 | INFO     | __main__:run:614 - Loading checkpoint...
Traceback (most recent call last):
  File "demo_mcmot.py", line 662, in <module>
    run(exp, args)
  File "demo_mcmot.py", line 618, in run
    model.load_state_dict(ckpt["model"])
  File "/home/nicken/.pyenv/versions/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for YOLOXDarknetReID:
        Unexpected key(s) in state_dict: "mtl_loss.sigma". 
```

run cmd: `python demo_mcmot.py -c ../latest_ckpt.pth.tar`

can you tell want happen？I want run this code to success in video

**Comment by CaptainEven** [comment]
Please use the latest DarknetCfg branch, sorry for not reminding!

**Comment by nicken** [comment]
OK  thanks
