### ISSUE TITLE
Still got error "Unexpected key(s) in state_dict: "mtl_loss.sigma", after change branch to DarknetCfg, and use the latest checkpoint

### ISSUE THREAD

**Issue by zhaoqyu** [CaptainEven/MCMOT-ByteTrack#11]
Still got error "Unexpected key(s) in state_dict: "mtl_loss.sigma", after change branch to DarknetCfg, and use the latest checkpoint 

Here is my command lin input and output info:
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/54652904/159700618-5bcf219d-31e6-4132-b2dc-bfbfacade02e.png">

(mcbytetrack) xys@a325xys:~/Downloads/zhaoqyu/code/MCMOT-ByteTrack_upd$ git checkout DarknetCfg
D	datasets/data_path/citypersons.train
D	datasets/data_path/eth.train
D	datasets/max_id_dict.npz
M	exps/example/mot/yolox_tiny_track_c5_darknet.py
M	tools/demo_mcmot.py
Already on 'DarknetCfg'
Your branch is up to date with 'origin/DarknetCfg'.
(mcbytetrack) xys@a325xys:~/Downloads/zhaoqyu/code/MCMOT-ByteTrack_upd$ python3 tools/demo_mcmot.py --reid True -f exps/example/mot/yolox_tiny_track_c5_darknet.py -c /home/xys/Downloads/zhaoqyu/code/MCMOT-ByteTrack_upd/pretrained/latest_ckpt.pth.tar --path /home/xys/Downloads/zhaoqyu/code/MCMOT-ByteTrack/datasets/tt.mp4
2022-03-23 20:35:23.957 | INFO     | yolox.exp.build:get_exp_by_file:17 - Exp file path: /home/xys/Downloads/zhaoqyu/code/MCMOT-ByteTrack_upd/exps/example/mot/yolox_tiny_track_c5_darknet.py.
2022-03-23 20:35:23.957 | INFO     | yolox.exp.build:get_exp_by_file:20 - Exp file's dir path: /home/xys/Downloads/zhaoqyu/code/MCMOT-ByteTrack_upd/exps/example/mot.
2022-03-23 20:35:23.957 | INFO     | yolox.exp.build:get_exp_by_file:25 - Module name: yolox_tiny_track_c5_darknet.
{0: 1266, 1: 313, 2: 490, 3: 758, 4: 82}
ReID:  False
Number of classes:  5
2022-03-23 20:35:23.958 | INFO     | __main__:run:586 - Args: Namespace(camid=0, ckpt='/home/xys/Downloads/zhaoqyu/code/MCMOT-ByteTrack_upd/pretrained/latest_ckpt.pth.tar', class_names=['car', ' bicycle', ' person', ' cyclist', ' tricycle'], conf=None, debug=True, demo='video', device='gpu', exp_file='exps/example/mot/yolox_tiny_track_c5_darknet.py', experiment_name='yolox_tiny_track_c5_darknet', fp16=False, fuse=False, match_thresh=0.8, min_box_area=10, mot20=False, n_classes=5, name=None, nms=None, path='/home/xys/Downloads/zhaoqyu/code/MCMOT-ByteTrack/datasets/tt.mp4', reid=True, save_result=True, task='track', track_buffer=240, track_thresh=0.5, trt=False, tsize=None, video_dir='../videos')
2022-03-23 20:35:23.961 | INFO     | yolox.models.yolox_darknet:__init__:753 - Network config file parsed.
2022-03-23 20:35:24.007 | INFO     | yolox.models.yolox_darknet:__init__:756 - Network modules built.
2022-03-23 20:35:24.007 | INFO     | yolox.models.yolox_darknet:__init__:760 - Network weights initialized.
2022-03-23 20:35:24.007 | INFO     | yolox.models.yolox_darknet:__init__:766 - Number of object classes: 5.
Net size:  (768, 448)
2022-03-23 20:35:24.007 | INFO     | yolox.models.yolox_darknet:__init__:773 - ReID: True
2022-03-23 20:35:25.498 | INFO     | __main__:run:614 - Loading checkpoint...
Traceback (most recent call last):
  File "tools/demo_mcmot.py", line 662, in <module>
    run(exp, args)
  File "tools/demo_mcmot.py", line 618, in run
    model.load_state_dict(ckpt["model"])
  File "/home/xys/anaconda3/envs/mcbytetrack/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for YOLOXDarknetReID:
	Unexpected key(s) in state_dict: "mtl_loss.sigma". 
(mcbytetrack) xys@a325xys:~/Downloads/zhaoqyu/code/MCMOT-ByteTrack_upd$

**Comment by zhaoqyu** [comment]
In yolox_darknet.py lint 797-804:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/54652904/159706984-9b26c947-e100-41a4-8ad6-569f0f9cf0b1.png">

The use_mtl = False as default. So we are not using mtl_loss  in the default code. But in the checkpoint file which we download by the link, there is mtl_loss, which is very strange , and caused the error below:
<img width="866" alt="image" src="https://user-images.githubusercontent.com/54652904/159707826-2c34d0ac-2f1a-45ba-b5e2-e1bce718f282.png">

**Comment by zhaoqyu** [comment]
But if I set use_mtl = True in yolox_tiny_track_c5_darknet.py line 82 like below:
<img width="533" alt="image" src="https://user-images.githubusercontent.com/54652904/159710889-7a1946fa-1a4b-492b-9ba4-07f0b4941fa6.png">

The code can run successful, but there will be no output in the video like below(no bbox output):
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/54652904/159710564-fb4cb115-25f7-4206-8546-a266188ae2e0.png">


Can you pls tell us how to fix this problem, or update a new version correct code, Thanks!!!!!!

**Comment by CaptainEven** [comment]
@LOVELACE01 Please use the DarknetCfg branch, and use demo_mcmot.py to test. In case of wrong weights file, i checked and re-loaded the checkpoint weights file link. You can download the test video i provided for verification.

**Comment by CaptainEven** [comment]
The following is my log:
```
/usr/bin/python3 -u /mnt/diskb/even/ByteTrack/tools/demo_mcmot.py
2022-03-24 09:27:47.985 | INFO     | yolox.exp.build:get_exp_by_file:17 - Exp file path: /mnt/diskb/even/ByteTrack/exps/example/mot/yolox_tiny_track_c5_darknet.py.
2022-03-24 09:27:47.986 | INFO     | yolox.exp.build:get_exp_by_file:20 - Exp file's dir path: /mnt/diskb/even/ByteTrack/exps/example/mot.
2022-03-24 09:27:47.986 | INFO     | yolox.exp.build:get_exp_by_file:25 - Module name: yolox_tiny_track_c5_darknet.
{0: 1266, 1: 313, 2: 490, 3: 758, 4: 82}
ReID:  False
Number of classes:  5
2022-03-24 09:27:47.991 | INFO     | __main__:run:586 - Args: Namespace(camid=0, ckpt='../YOLOX_outputs/yolox_tiny_track_c5_darknet/latest_ckpt.pth.tar', class_names=['car', ' bicycle', ' person', ' cyclist', ' tricycle'], conf=None, debug=True, demo='video', device='gpu', exp_file='../exps/example/mot/yolox_tiny_track_c5_darknet.py', experiment_name='yolox_tiny_track_c5_darknet', fp16=False, fuse=False, match_thresh=0.8, min_box_area=10, mot20=False, n_classes=5, name=None, nms=None, path='../videos/test_13.mp4', reid=False, save_result=True, task='track', track_buffer=240, track_thresh=0.5, trt=False, tsize=None, video_dir='../videos')
2022-03-24 09:27:47.995 | INFO     | yolox.models.yolox_darknet:__init__:753 - Network config file parsed.
2022-03-24 09:27:48.067 | INFO     | yolox.models.yolox_darknet:__init__:756 - Network modules built.
2022-03-24 09:27:48.067 | INFO     | yolox.models.yolox_darknet:__init__:760 - Network weights initialized.
2022-03-24 09:27:48.067 | INFO     | yolox.models.yolox_darknet:__init__:766 - Number of object classes: 5.
Net size:  (768, 448)
2022-03-24 09:27:48.068 | INFO     | yolox.models.yolox_darknet:__init__:773 - ReID: True
2022-03-24 09:27:51.564 | INFO     | __main__:run:614 - Loading checkpoint...
2022-03-24 09:27:51.663 | INFO     | __main__:run:619 - Checkpoint /mnt/diskb/even/ByteTrack/YOLOX_outputs/yolox_tiny_track_c5_darknet/latest_ckpt.pth.tar loaded done.
Start tracking video test_13 offline...
args:
 Namespace(camid=0, ckpt='../YOLOX_outputs/yolox_tiny_track_c5_darknet/latest_ckpt.pth.tar', class_names=['car', ' bicycle', ' person', ' cyclist', ' tricycle'], conf=None, debug=True, demo='video', device='gpu', exp_file='../exps/example/mot/yolox_tiny_track_c5_darknet.py', experiment_name='yolox_tiny_track_c5_darknet', fp16=False, fuse=False, match_thresh=0.8, min_box_area=10, mot20=False, n_classes=5, name=None, nms=None, path='/mnt/diskb/even/ByteTrack/videos/test_13.mp4', reid=False, save_result=True, task='track', track_buffer=240, track_thresh=0.5, trt=False, tsize=None, video_dir='../videos')
Tracker's low det thresh:  0.1
Tracker's high det thresh:  0.5
Tracker's high match thresh:  0.8
Tracker's low match thresh:  0.5
Tracker's unconfirmed match thresh:  0.7
Tracker's new track thresh:  0.6
Tracker's buffer size:  240
2022-03-24 09:27:51.733 | INFO     | __main__:video_tracking:414 - Processing frame 000/566 | fps 30.00
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
2022-03-24 09:27:54.286 | INFO     | __main__:video_tracking:409 - Processing frame 030/566 | fps 47.39
2022-03-24 09:27:56.515 | INFO     | __main__:video_tracking:409 - Processing frame 060/566 | fps 47.96
2022-03-24 09:27:58.767 | INFO     | __main__:video_tracking:409 - Processing frame 090/566 | fps 47.99
2022-03-24 09:28:00.987 | INFO     | __main__:video_tracking:409 - Processing frame 120/566 | fps 47.86
2022-03-24 09:28:03.127 | INFO     | __main__:video_tracking:409 - Processing frame 150/566 | fps 48.09
2022-03-24 09:28:06.012 | INFO     | __main__:video_tracking:409 - Processing frame 180/566 | fps 46.80
2022-03-24 09:28:08.406 | INFO     | __main__:video_tracking:409 - Processing frame 210/566 | fps 46.92
2022-03-24 09:28:10.677 | INFO     | __main__:video_tracking:409 - Processing frame 240/566 | fps 47.27
2022-03-24 09:28:12.905 | INFO     | __main__:video_tracking:409 - Processing frame 270/566 | fps 47.66
2022-03-24 09:28:15.110 | INFO     | __main__:video_tracking:409 - Processing frame 300/566 | fps 48.00
2022-03-24 09:28:17.281 | INFO     | __main__:video_tracking:409 - Processing frame 330/566 | fps 48.44
2022-03-24 09:28:19.505 | INFO     | __main__:video_tracking:409 - Processing frame 360/566 | fps 48.75
2022-03-24 09:28:21.706 | INFO     | __main__:video_tracking:409 - Processing frame 390/566 | fps 49.09
2022-03-24 09:28:23.853 | INFO     | __main__:video_tracking:409 - Processing frame 420/566 | fps 49.52
2022-03-24 09:28:26.007 | INFO     | __main__:video_tracking:409 - Processing frame 450/566 | fps 49.94
2022-03-24 09:28:28.307 | INFO     | __main__:video_tracking:409 - Processing frame 480/566 | fps 50.21
2022-03-24 09:28:30.591 | INFO     | __main__:video_tracking:409 - Processing frame 510/566 | fps 50.47
2022-03-24 09:28:32.829 | INFO     | __main__:video_tracking:409 - Processing frame 540/566 | fps 50.69
Read frame 563 failed!
/mnt/diskb/even/ByteTrack/tools/YOLOX_outputs/yolox_tiny_track_c5_darknet/track_vis/test_13/2022_03_24_09_27_51.mp4 saved.
test_13 tracking done offline.

Process finished with exit code 0
```

**Comment by zhaoqyu** [comment]
> The following is my log:
> 
> ```
> /usr/bin/python3 -u /mnt/diskb/even/ByteTrack/tools/demo_mcmot.py
> 2022-03-24 09:27:47.985 | INFO     | yolox.exp.build:get_exp_by_file:17 - Exp file path: /mnt/diskb/even/ByteTrack/exps/example/mot/yolox_tiny_track_c5_darknet.py.
> 2022-03-24 09:27:47.986 | INFO     | yolox.exp.build:get_exp_by_file:20 - Exp file's dir path: /mnt/diskb/even/ByteTrack/exps/example/mot.
> 2022-03-24 09:27:47.986 | INFO     | yolox.exp.build:get_exp_by_file:25 - Module name: yolox_tiny_track_c5_darknet.
> {0: 1266, 1: 313, 2: 490, 3: 758, 4: 82}
> ReID:  False
> Number of classes:  5
> 2022-03-24 09:27:47.991 | INFO     | __main__:run:586 - Args: Namespace(camid=0, ckpt='../YOLOX_outputs/yolox_tiny_track_c5_darknet/latest_ckpt.pth.tar', class_names=['car', ' bicycle', ' person', ' cyclist', ' tricycle'], conf=None, debug=True, demo='video', device='gpu', exp_file='../exps/example/mot/yolox_tiny_track_c5_darknet.py', experiment_name='yolox_tiny_track_c5_darknet', fp16=False, fuse=False, match_thresh=0.8, min_box_area=10, mot20=False, n_classes=5, name=None, nms=None, path='../videos/test_13.mp4', reid=False, save_result=True, task='track', track_buffer=240, track_thresh=0.5, trt=False, tsize=None, video_dir='../videos')
> 2022-03-24 09:27:47.995 | INFO     | yolox.models.yolox_darknet:__init__:753 - Network config file parsed.
> 2022-03-24 09:27:48.067 | INFO     | yolox.models.yolox_darknet:__init__:756 - Network modules built.
> 2022-03-24 09:27:48.067 | INFO     | yolox.models.yolox_darknet:__init__:760 - Network weights initialized.
> 2022-03-24 09:27:48.067 | INFO     | yolox.models.yolox_darknet:__init__:766 - Number of object classes: 5.
> Net size:  (768, 448)
> 2022-03-24 09:27:48.068 | INFO     | yolox.models.yolox_darknet:__init__:773 - ReID: True
> 2022-03-24 09:27:51.564 | INFO     | __main__:run:614 - Loading checkpoint...
> 2022-03-24 09:27:51.663 | INFO     | __main__:run:619 - Checkpoint /mnt/diskb/even/ByteTrack/YOLOX_outputs/yolox_tiny_track_c5_darknet/latest_ckpt.pth.tar loaded done.
> Start tracking video test_13 offline...
> args:
>  Namespace(camid=0, ckpt='../YOLOX_outputs/yolox_tiny_track_c5_darknet/latest_ckpt.pth.tar', class_names=['car', ' bicycle', ' person', ' cyclist', ' tricycle'], conf=None, debug=True, demo='video', device='gpu', exp_file='../exps/example/mot/yolox_tiny_track_c5_darknet.py', experiment_name='yolox_tiny_track_c5_darknet', fp16=False, fuse=False, match_thresh=0.8, min_box_area=10, mot20=False, n_classes=5, name=None, nms=None, path='/mnt/diskb/even/ByteTrack/videos/test_13.mp4', reid=False, save_result=True, task='track', track_buffer=240, track_thresh=0.5, trt=False, tsize=None, video_dir='../videos')
> Tracker's low det thresh:  0.1
> Tracker's high det thresh:  0.5
> Tracker's high match thresh:  0.8
> Tracker's low match thresh:  0.5
> Tracker's unconfirmed match thresh:  0.7
> Tracker's new track thresh:  0.6
> Tracker's buffer size:  240
> 2022-03-24 09:27:51.733 | INFO     | __main__:video_tracking:414 - Processing frame 000/566 | fps 30.00
> /usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
>   return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
> 2022-03-24 09:27:54.286 | INFO     | __main__:video_tracking:409 - Processing frame 030/566 | fps 47.39
> 2022-03-24 09:27:56.515 | INFO     | __main__:video_tracking:409 - Processing frame 060/566 | fps 47.96
> 2022-03-24 09:27:58.767 | INFO     | __main__:video_tracking:409 - Processing frame 090/566 | fps 47.99
> 2022-03-24 09:28:00.987 | INFO     | __main__:video_tracking:409 - Processing frame 120/566 | fps 47.86
> 2022-03-24 09:28:03.127 | INFO     | __main__:video_tracking:409 - Processing frame 150/566 | fps 48.09
> 2022-03-24 09:28:06.012 | INFO     | __main__:video_tracking:409 - Processing frame 180/566 | fps 46.80
> 2022-03-24 09:28:08.406 | INFO     | __main__:video_tracking:409 - Processing frame 210/566 | fps 46.92
> 2022-03-24 09:28:10.677 | INFO     | __main__:video_tracking:409 - Processing frame 240/566 | fps 47.27
> 2022-03-24 09:28:12.905 | INFO     | __main__:video_tracking:409 - Processing frame 270/566 | fps 47.66
> 2022-03-24 09:28:15.110 | INFO     | __main__:video_tracking:409 - Processing frame 300/566 | fps 48.00
> 2022-03-24 09:28:17.281 | INFO     | __main__:video_tracking:409 - Processing frame 330/566 | fps 48.44
> 2022-03-24 09:28:19.505 | INFO     | __main__:video_tracking:409 - Processing frame 360/566 | fps 48.75
> 2022-03-24 09:28:21.706 | INFO     | __main__:video_tracking:409 - Processing frame 390/566 | fps 49.09
> 2022-03-24 09:28:23.853 | INFO     | __main__:video_tracking:409 - Processing frame 420/566 | fps 49.52
> 2022-03-24 09:28:26.007 | INFO     | __main__:video_tracking:409 - Processing frame 450/566 | fps 49.94
> 2022-03-24 09:28:28.307 | INFO     | __main__:video_tracking:409 - Processing frame 480/566 | fps 50.21
> 2022-03-24 09:28:30.591 | INFO     | __main__:video_tracking:409 - Processing frame 510/566 | fps 50.47
> 2022-03-24 09:28:32.829 | INFO     | __main__:video_tracking:409 - Processing frame 540/566 | fps 50.69
> Read frame 563 failed!
> /mnt/diskb/even/ByteTrack/tools/YOLOX_outputs/yolox_tiny_track_c5_darknet/track_vis/test_13/2022_03_24_09_27_51.mp4 saved.
> test_13 tracking done offline.
> 
> Process finished with exit code 0
> ```

Solved my problem, really appreciate for your help!!!  Great work!!!
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/54652904/159828818-05839005-5f8c-4ac5-a2f2-c0151e3897c9.png">
<img width="954" alt="image" src="https://user-images.githubusercontent.com/54652904/159828837-289ccd4b-6b77-4b65-8a8d-a74563d406df.png">
