### ISSUE TITLE
queries on reid

### ISSUE THREAD

**Issue by abhigoku10** [CaptainEven/MCMOT-ByteTrack#4]
@CaptainEven  hi thanks for sharing the code base i had following queries 
1. had reid been added as an additional head to the yolox architecture ? 
2. If so can you share the location of the addition module 
3. the current repo does tracking for 5 classes ? does it do reid for those 5 classes also ?

Thnaks for the response

**Comment by CaptainEven** [comment]
@abhigoku10 yolox_darknet.py, yolox_reid.py, yolox_head_reid.py

**Comment by zoucg** [comment]
> ei



> @abhigoku10 yolox_darknet.py, yolox_reid.py, yolox_head_reid.py

I can't find these files

**Comment by zoucg** [comment]
> @zoucg [MCMOT-ByteTrack](https://github.com/CaptainEven/MCMOT-ByteTrack)/[yolox](https://github.com/CaptainEven/MCMOT-ByteTrack/tree/master/yolox)/[models](https://github.com/CaptainEven/MCMOT-ByteTrack/tree/master/yolox/models)/

thank you ,I find ,
but when I excule 'python demo_track.py -f ../exps/example/mot/yolox_tiny_det_c5_darknet.py  -c ../model/latest_ckpt.pth.tar'

this error occured:
RuntimeError: Error(s) in loading state_dict for YOLOXDarknet:
        Unexpected key(s) in state_dict: "reid_classifiers.0.weight", "reid_classifiers.0.bias", "reid_classifiers.1.weight", "reid_classifiers.1.bias", "reid_classifiers.2.weight", "reid_classifiers.2.bias", "reid_classifiers.3.weight", "reid_classifiers.3.bias", "reid_classifiers.4.weight", "reid_classifiers.4.bias", "mtl_loss.sigma".

**Comment by zoucg** [comment]
> > @zoucg [MCMOT-ByteTrack](https://github.com/CaptainEven/MCMOT-ByteTrack)/[yolox](https://github.com/CaptainEven/MCMOT-ByteTrack/tree/master/yolox)/[models](https://github.com/CaptainEven/MCMOT-ByteTrack/tree/master/yolox/models)/
> 
> thank you ,I find , but when I excule 'python demo_track.py -f ../exps/example/mot/yolox_tiny_det_c5_darknet.py -c ../model/latest_ckpt.pth.tar'
> 
> this error occured: RuntimeError: Error(s) in loading state_dict for YOLOXDarknet: Unexpected key(s) in state_dict: "reid_classifiers.0.weight", "reid_classifiers.0.bias", "reid_classifiers.1.weight", "reid_classifiers.1.bias", "reid_classifiers.2.weight", "reid_classifiers.2.bias", "reid_classifiers.3.weight", "reid_classifiers.3.bias", "reid_classifiers.4.weight", "reid_classifiers.4.bias", "mtl_loss.sigma".

it seem that this architecture don't match the pretrained model

**Comment by CaptainEven** [comment]
@zoucg My log as follows:
2022-02-11 17:49:35.437 | INFO     | yolox.exp.build:get_exp_by_file:17 - Exp file path: /mnt/diskb/even/ByteTrack/exps/example/mot/yolox_tiny_track_c5_darknet.py.
2022-02-11 17:49:35.438 | INFO     | yolox.exp.build:get_exp_by_file:20 - Exp file's dir path: /mnt/diskb/even/ByteTrack/exps/example/mot.
2022-02-11 17:49:35.438 | INFO     | yolox.exp.build:get_exp_by_file:25 - Module name: yolox_tiny_track_c5_darknet.
{0: 1266, 1: 313, 2: 490, 3: 758, 4: 82}
ReID:  False
Number of classes:  5
2022-02-11 17:49:35.446 | INFO     | __main__:run:585 - Args: Namespace(camid=0, ckpt='../YOLOX_outputs/yolox_tiny_track_c5_darknet/latest_ckpt.pth.tar', class_names=['car', ' bicycle', ' person', ' cyclist', ' tricycle'], conf=None, debug=True, demo='video', device='gpu', exp_file='../exps/example/mot/yolox_tiny_track_c5_darknet.py', experiment_name='yolox_tiny_track_c5_darknet', fp16=False, fuse=False, match_thresh=0.8, min_box_area=10, mot20=False, n_classes=5, name=None, nms=None, path='../videos/test_13.mp4', reid=True, save_result=True, task='track', track_buffer=240, track_thresh=0.5, trt=False, tsize=None, video_dir='../videos')
2022-02-11 17:49:35.453 | INFO     | yolox.models.yolox_darknet:__init__:753 - Network config file parsed.
2022-02-11 17:49:35.569 | INFO     | yolox.models.yolox_darknet:__init__:756 - Network modules built.
2022-02-11 17:49:35.569 | INFO     | yolox.models.yolox_darknet:__init__:760 - Network weights initialized.
2022-02-11 17:49:35.569 | INFO     | yolox.models.yolox_darknet:__init__:766 - Number of object classes: 5.
Net size:  (768, 448)
2022-02-11 17:49:35.570 | INFO     | yolox.models.yolox_darknet:__init__:773 - ReID: True
2022-02-11 17:49:39.477 | INFO     | __main__:run:613 - Loading checkpoint...
2022-02-11 17:49:39.581 | INFO     | __main__:run:618 - Checkpoint /mnt/diskb/even/ByteTrack/YOLOX_outputs/yolox_tiny_track_c5_darknet/latest_ckpt.pth.tar loaded done.
Start tracking video test_13 offline...
args:
 Namespace(camid=0, ckpt='../YOLOX_outputs/yolox_tiny_track_c5_darknet/latest_ckpt.pth.tar', class_names=['car', ' bicycle', ' person', ' cyclist', ' tricycle'], conf=None, debug=True, demo='video', device='gpu', exp_file='../exps/example/mot/yolox_tiny_track_c5_darknet.py', experiment_name='yolox_tiny_track_c5_darknet', fp16=False, fuse=False, match_thresh=0.8, min_box_area=10, mot20=False, n_classes=5, name=None, nms=None, path='/mnt/diskb/even/ByteTrack/videos/test_13.mp4', reid=True, save_result=True, task='track', track_buffer=240, track_thresh=0.5, trt=False, tsize=None, video_dir='../videos')
Tracker's low det thresh:  0.1
Tracker's high det thresh:  0.5
Tracker's high match thresh:  0.8
Tracker's low match thresh:  0.5
Tracker's unconfirmed match thresh:  0.7
Tracker's new track thresh:  0.6
Tracker's buffer size:  240
2022-02-11 17:49:39.666 | INFO     | __main__:video_tracking:414 - Processing frame 000/566 | fps 30.00
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
2022-02-11 17:49:42.744 | INFO     | __main__:video_tracking:409 - Processing frame 030/566 | fps 27.32
2022-02-11 17:49:45.705 | INFO     | __main__:video_tracking:409 - Processing frame 060/566 | fps 25.97
2022-02-11 17:49:48.712 | INFO     | __main__:video_tracking:409 - Processing frame 090/566 | fps 25.25
2022-02-11 17:49:51.726 | INFO     | __main__:video_tracking:409 - Processing frame 120/566 | fps 24.90
2022-02-11 17:49:55.080 | INFO     | __main__:video_tracking:409 - Processing frame 150/566 | fps 24.27
2022-02-11 17:49:58.105 | INFO     | __main__:video_tracking:409 - Processing frame 180/566 | fps 24.25
2022-02-11 17:50:01.178 | INFO     | __main__:video_tracking:409 - Processing frame 210/566 | fps 24.34
2022-02-11 17:50:04.158 | INFO     | __main__:video_tracking:409 - Processing frame 240/566 | fps 24.52
2022-02-11 17:50:06.994 | INFO     | __main__:video_tracking:409 - Processing frame 270/566 | fps 24.75
2022-02-11 17:50:09.766 | INFO     | __main__:video_tracking:409 - Processing frame 300/566 | fps 25.11
2022-02-11 17:50:12.305 | INFO     | __main__:video_tracking:409 - Processing frame 330/566 | fps 25.64
2022-02-11 17:50:14.983 | INFO     | __main__:video_tracking:409 - Processing frame 360/566 | fps 25.98
2022-02-11 17:50:17.582 | INFO     | __main__:video_tracking:409 - Processing frame 390/566 | fps 26.33
2022-02-11 17:50:20.187 | INFO     | __main__:video_tracking:409 - Processing frame 420/566 | fps 26.67
2022-02-11 17:50:22.833 | INFO     | __main__:video_tracking:409 - Processing frame 450/566 | fps 26.95
2022-02-11 17:50:25.765 | INFO     | __main__:video_tracking:409 - Processing frame 480/566 | fps 27.06
2022-02-11 17:50:28.613 | INFO     | __main__:video_tracking:409 - Processing frame 510/566 | fps 27.17
2022-02-11 17:50:31.281 | INFO     | __main__:video_tracking:409 - Processing frame 540/566 | fps 27.32
Read frame 563 failed!
/mnt/diskb/even/ByteTrack/tools/YOLOX_outputs/yolox_tiny_track_c5_darknet/track_vis/test_13/2022_02_11_17_49_39.mp4 saved.
test_13 tracking done offline.

I will check the error next week.

**Comment by zoucg** [comment]
> @zoucg My log as follows: 2022-02-11 17:49:35.437 | INFO | yolox.exp.build:get_exp_by_file:17 - Exp file path: /mnt/diskb/even/ByteTrack/exps/example/mot/yolox_tiny_track_c5_darknet.py. 2022-02-11 17:49:35.438 | INFO | yolox.exp.build:get_exp_by_file:20 - Exp file's dir path: /mnt/diskb/even/ByteTrack/exps/example/mot. 2022-02-11 17:49:35.438 | INFO | yolox.exp.build:get_exp_by_file:25 - Module name: yolox_tiny_track_c5_darknet. {0: 1266, 1: 313, 2: 490, 3: 758, 4: 82} ReID: False Number of classes: 5 2022-02-11 17:49:35.446 | INFO | **main**:run:585 - Args: Namespace(camid=0, ckpt='../YOLOX_outputs/yolox_tiny_track_c5_darknet/latest_ckpt.pth.tar', class_names=['car', ' bicycle', ' person', ' cyclist', ' tricycle'], conf=None, debug=True, demo='video', device='gpu', exp_file='../exps/example/mot/yolox_tiny_track_c5_darknet.py', experiment_name='yolox_tiny_track_c5_darknet', fp16=False, fuse=False, match_thresh=0.8, min_box_area=10, mot20=False, n_classes=5, name=None, nms=None, path='../videos/test_13.mp4', reid=True, save_result=True, task='track', track_buffer=240, track_thresh=0.5, trt=False, tsize=None, video_dir='../videos') 2022-02-11 17:49:35.453 | INFO | yolox.models.yolox_darknet:**init**:753 - Network config file parsed. 2022-02-11 17:49:35.569 | INFO | yolox.models.yolox_darknet:**init**:756 - Network modules built. 2022-02-11 17:49:35.569 | INFO | yolox.models.yolox_darknet:**init**:760 - Network weights initialized. 2022-02-11 17:49:35.569 | INFO | yolox.models.yolox_darknet:**init**:766 - Number of object classes: 5. Net size: (768, 448) 2022-02-11 17:49:35.570 | INFO | yolox.models.yolox_darknet:**init**:773 - ReID: True 2022-02-11 17:49:39.477 | INFO | **main**:run:613 - Loading checkpoint... 2022-02-11 17:49:39.581 | INFO | **main**:run:618 - Checkpoint /mnt/diskb/even/ByteTrack/YOLOX_outputs/yolox_tiny_track_c5_darknet/latest_ckpt.pth.tar loaded done. Start tracking video test_13 offline... args: Namespace(camid=0, ckpt='../YOLOX_outputs/yolox_tiny_track_c5_darknet/latest_ckpt.pth.tar', class_names=['car', ' bicycle', ' person', ' cyclist', ' tricycle'], conf=None, debug=True, demo='video', device='gpu', exp_file='../exps/example/mot/yolox_tiny_track_c5_darknet.py', experiment_name='yolox_tiny_track_c5_darknet', fp16=False, fuse=False, match_thresh=0.8, min_box_area=10, mot20=False, n_classes=5, name=None, nms=None, path='/mnt/diskb/even/ByteTrack/videos/test_13.mp4', reid=True, save_result=True, task='track', track_buffer=240, track_thresh=0.5, trt=False, tsize=None, video_dir='../videos') Tracker's low det thresh: 0.1 Tracker's high det thresh: 0.5 Tracker's high match thresh: 0.8 Tracker's low match thresh: 0.5 Tracker's unconfirmed match thresh: 0.7 Tracker's new track thresh: 0.6 Tracker's buffer size: 240 2022-02-11 17:49:39.666 | INFO | **main**:video_tracking:414 - Processing frame 000/566 | fps 30.00 /usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /pytorch/c10/core/TensorImpl.h:1156.) return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode) 2022-02-11 17:49:42.744 | INFO | **main**:video_tracking:409 - Processing frame 030/566 | fps 27.32 2022-02-11 17:49:45.705 | INFO | **main**:video_tracking:409 - Processing frame 060/566 | fps 25.97 2022-02-11 17:49:48.712 | INFO | **main**:video_tracking:409 - Processing frame 090/566 | fps 25.25 2022-02-11 17:49:51.726 | INFO | **main**:video_tracking:409 - Processing frame 120/566 | fps 24.90 2022-02-11 17:49:55.080 | INFO | **main**:video_tracking:409 - Processing frame 150/566 | fps 24.27 2022-02-11 17:49:58.105 | INFO | **main**:video_tracking:409 - Processing frame 180/566 | fps 24.25 2022-02-11 17:50:01.178 | INFO | **main**:video_tracking:409 - Processing frame 210/566 | fps 24.34 2022-02-11 17:50:04.158 | INFO | **main**:video_tracking:409 - Processing frame 240/566 | fps 24.52 2022-02-11 17:50:06.994 | INFO | **main**:video_tracking:409 - Processing frame 270/566 | fps 24.75 2022-02-11 17:50:09.766 | INFO | **main**:video_tracking:409 - Processing frame 300/566 | fps 25.11 2022-02-11 17:50:12.305 | INFO | **main**:video_tracking:409 - Processing frame 330/566 | fps 25.64 2022-02-11 17:50:14.983 | INFO | **main**:video_tracking:409 - Processing frame 360/566 | fps 25.98 2022-02-11 17:50:17.582 | INFO | **main**:video_tracking:409 - Processing frame 390/566 | fps 26.33 2022-02-11 17:50:20.187 | INFO | **main**:video_tracking:409 - Processing frame 420/566 | fps 26.67 2022-02-11 17:50:22.833 | INFO | **main**:video_tracking:409 - Processing frame 450/566 | fps 26.95 2022-02-11 17:50:25.765 | INFO | **main**:video_tracking:409 - Processing frame 480/566 | fps 27.06 2022-02-11 17:50:28.613 | INFO | **main**:video_tracking:409 - Processing frame 510/566 | fps 27.17 2022-02-11 17:50:31.281 | INFO | **main**:video_tracking:409 - Processing frame 540/566 | fps 27.32 Read frame 563 failed! /mnt/diskb/even/ByteTrack/tools/YOLOX_outputs/yolox_tiny_track_c5_darknet/track_vis/test_13/2022_02_11_17_49_39.mp4 saved. test_13 tracking done offline.
> 
> I will check the error next week.

thanks for your reply ,I have solved this problem,but a new error occured:
2022-02-14 09:34:11.429 | INFO     | yolox.exp.build:get_exp_by_file:17 - Exp file path: /home/zoucaigang/cv_project/MCMOT-ByteTrack/exps/example/mot/yolox_tiny_track_c5_darknet.py.
2022-02-14 09:34:11.430 | INFO     | yolox.exp.build:get_exp_by_file:20 - Exp file's dir path: /home/zoucaigang/cv_project/MCMOT-ByteTrack/exps/example/mot.
2022-02-14 09:34:11.430 | INFO     | yolox.exp.build:get_exp_by_file:25 - Module name: yolox_tiny_track_c5_darknet.
{0: 1266, 1: 313, 2: 490, 3: 758, 4: 82}
ReID:  False
Number of classes:  5
2022-02-14 09:34:11.435 | INFO     | __main__:run:582 - Args: Namespace(camid=0, ckpt='../model/latest_ckpt.pth.tar', class_names=['car', ' bicycle', ' person', ' cyclist', ' tricycle'], conf=None, debug=True, demo='video', device='gpu', exp_file='../exps/example/mot/yolox_tiny_track_c5_darknet.py', experiment_name='yolox_tiny_track_c5_darknet', fp16=False, fuse=False, match_thresh=0.8, min_box_area=10, mot20=False, n_classes=5, name=None, nms=None, path='../videos/test_13.mp4', reid=True, save_result=True, task='track', track_buffer=240, track_thresh=0.5, trt=False, tsize=None, video_dir='../videos')
2022-02-14 09:34:11.439 | INFO     | yolox.models.yolox_darknet:__init__:753 - Network config file parsed.
2022-02-14 09:34:11.501 | INFO     | yolox.models.yolox_darknet:__init__:756 - Network modules built.
2022-02-14 09:34:11.501 | INFO     | yolox.models.yolox_darknet:__init__:760 - Network weights initialized.
2022-02-14 09:34:11.502 | INFO     | yolox.models.yolox_darknet:__init__:766 - Number of object classes: 5.
Net size:  (768, 448)
2022-02-14 09:34:11.502 | INFO     | yolox.models.yolox_darknet:__init__:773 - ReID: True
2022-02-14 09:34:14.304 | INFO     | __main__:run:610 - Loading checkpoint...
Traceback (most recent call last):
  File "demo_mcmot.py", line 658, in <module>
    run(exp, args)
  File "demo_mcmot.py", line 614, in run
    model.load_state_dict(ckpt["model"])
  File "/home/zoucaigang/.conda/envs/zcgcv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for YOLOXDarknetReID:
        Unexpected key(s) in state_dict: "mtl_loss.sigma".

**Comment by CaptainEven** [comment]
@abhigoku10 Please update the code to  the latest version and run the demo again. Let me know if any error occured. Good luck!

**Comment by zoucg** [comment]
> @abhigoku10 Please update the code to the latest version and run the demo again. Let me know if any error occured. Good luck!

i update it to the latest version,but it still the error

**Comment by ZacharyZgw** [comment]
@CaptainEven I also meet the same error.
RuntimeError: Error(s) in loading state_dict for YOLOXDarknetReID:
![image](https://user-images.githubusercontent.com/24191547/154924457-f28acdf6-db9b-4815-a921-690dbf67c1c9.png)

**Comment by CaptainEven** [comment]
@abhigoku10 @ZacharyZgw @zoucg My fault! You guys shoud run demo_mcmot.py

**Comment by nicken** [comment]
> @abhigoku10 @ZacharyZgw @zoucg My fault! You guys shoud run demo_mcmot.py

but He's actually running this code! now i get same proplem, can you help us?
@CaptainEven

**Comment by CaptainEven** [comment]
@abhigoku10 @ZacharyZgw @zoucg @nicken My fault! You guys shoud run demo_mcmot.py

Use the DarknetCfg Branch please and run demo_mcmot.py, sorry for not reminding that!

**Comment by zhaoqyu** [comment]
> 

Used your new updated code, but Still got this error!!!, Here is my command line output:
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/54652904/159692828-9bed45f8-dc61-4462-8f02-a70d392a4c1b.png">
My command line input is :
python3 tools/demo_mcmot.py --reid True -f exps/example/mot/yolox_tiny_track_c5_darknet.py -c /home/xys/Downloads/zhaoqyu/code/MCMOT-ByteTrack_upd/pretrained/latest_ckpt.pth.tar --path /home/xys/Downloads/zhaoqyu/code/MCMOT-ByteTrack/datasets/tt.mp4

It seems like you make some changes in your local code, but not updated in github,  definetely not just in demo_mcmot.py


Can you pls check the whole project code, cause it surely cannot run,  thanks a lot for your wonderful work!

**Comment by zhaoqyu** [comment]
Can you pls tell us how to use this '"DarknetCfg Branch ",  how to change your code , or Just run your newly updated demo_mcmot.py is fine, please. thanks a lot for your kindness.

**Comment by CaptainEven** [comment]
@abhigoku10 @ZacharyZgw @zoucg @nicken Please refer to Issue #11, LOVELACE01 test succeeded.
