### ISSUE TITLE
Run demo_mcmot.py IndexError: index 1 is out of bounds for dimension 0 with size 1

### ISSUE THREAD

**Issue by apol-fumio-moriya** [CaptainEven/MCMOT-ByteTrack#9]
I am trying to train with the following commands.

```
! wget https://github.com/Megvii-BaseDetection/storage/releases/download/0.0.1/yolox_tiny_32dot8.pth -P ../YOLOX_outputs/yolox_tiny_track_c5_darknet/
! python3 train_det.py -d 0 -b 16 -o --data_dir ../yolox/data/datasets/coco128 -c ../YOLOX_outputs/yolox_tiny_track_c5_darknet/yolox_tiny_32dot8.pth
```

However, an error occurs.

`[Err]: invalid file list path!`

Where can I find the following files?

train_f_list_path        '/users/duanyou/c5/data_all/train_all.txt'
test_f_list_path         '/users/duanyou/c5/data_all/test5000.txt'

Please advise me.

**Comment by apol-fumio-moriya** [comment]
I proceeded to run the demo, but an error occurred.

`! python3 demo_mcmot.py --demo video -debug True --n_classes 1 --class_names person --ckpt ../YOLOX_outputs/yolox_tiny_det_c5_darknet/latest_ckpt.pth.tar --video_dir /home/ubuntu/work/sample_data/ --reid true --path /home/ubuntu/work/sample_data/IMG_0017.MOV`

```
2022-03-23 10:03:25.886 | INFO     | __main__:video_tracking:417 - Processing frame 000/714 | fps 30.00
/home/ubuntu/.local/lib/python3.6/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "demo_mcmot.py", line 665, in <module>
    run(exp, args)
  File "demo_mcmot.py", line 651, in run
    imageflow_demo(predictor, vis_dir, current_time, args)
  File "demo_mcmot.py", line 557, in imageflow_demo
    video_tracking(predictor, cap, save_path, args)
  File "demo_mcmot.py", line 424, in video_tracking
    outputs, feature_map, img_info = predictor.inference(frame, timer)
  File "demo_mcmot.py", line 283, in inference
    outputs, feature_map = outputs[0], outputs[1]
IndexError: index 1 is out of bounds for dimension 0 with size 1
```

Please advise me.

**Comment by CaptainEven** [comment]
@apol-fumio-moriya Use The latest DarknetCfg Branch please.

**Comment by CaptainEven** [comment]
@apol-fumio-moriya You can refer to Issue  #11, he test the demo succeeded.
